export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const SOURCE_LOADED = 'SOURCE_LOADED';
export const CLEAR_SOURCES = 'CLEAR_SOURCES';
export const DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED';

export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const VOTED = 'VOTED';
export const VOTE_CLEARED = 'VOTE_CLEARED';
export const VOTE_RECEIVED = 'VOTE_RECEIVED';
export const VOTE_UPLOADED = 'VOTE_UPLOADED';
export const VOTES_RECEIVED = 'VOTES_RECEIVED';

export const REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS';
export const NOTIFICATIONS_RECEIVED = 'NOTIFICATIONS_RECEIVED';

export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const FRIENDS_RECEIVED = 'FRIENDS_RECEIVED';

export const SETUP_SOCKET = 'SETUP_SOCKET';
