export const STORE_TOKEN = 'STORE_TOKEN';
export const SOURCE_LOADED = 'SOURCE_LOADED';
export const TAB_SELECTED = 'TAB_SELECTED';
export const DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED';

export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
